### ISSUE TITLE
Add credentials.json and secrets.py to gitignore

### ISSUE THREAD

**Issue by RakinRkz** [L1ghtweight/netman#1]
Readme might need to be modified for adding these files manually.

**Comment by RakinRkz** [comment]
Readme might need to be modified for adding these files manually.

**Comment by shahnewaz-labib** [comment]
@RakinRkz  Can you please fix it and make it a PR?

**Comment by RakinRkz** [comment]
@shahnewaz-labib Please check the PR: #3

**Comment by shahnewaz-labib** [comment]
merged
